version: "3.2"
services:
  mssql:
    build: ./database
    container_name: mssql
    hostname: mssql
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=SuperStrongPassword123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    volumes:
      - mssql-data:/var/opt/mssql
    networks: 
      - mssql

volumes:
    mssql-data:

networks: 
  mssql:
    name: mssql
    driver: bridge