version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    networks:
      - frankpress
    depends_on:
      - mssql

  mssql:
    image: ${DOCKER_REGISTRY-}mssql
    container_name: mssql
    build: 
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=SuperStrongPassword123
      - ACCEPT_EULA=Y
    volumes:
      - mssql-data:/var/opt/mssql
    networks: 
      - frankpress

volumes:
  mssql-data:

networks: 
  frankpress:
    name: frankpress
    driver: bridge