FROM mcr.microsoft.com/mssql/server

COPY database/create_database.sql create_database.sql
COPY database/setup_database.sh setup_database.sh
COPY database/entrypoint.sh entrypoint.sh

CMD /bin/bash ./entrypoint.sh